In [69]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from src.user_recommender import ReviewRecommender
from src.item_reccomender import ItemRecommender
#from src.make_ratings_matrix import ratings_mat

In [4]:
specials = pd.read_pickle('data/working_corpus.pkl')
reviews = pd.read_pickle('data/working_reviews.pkl')

In [71]:
tf = TfidfVectorizer(max_features=10000, max_df=0.9, ngram_range=(3,10))
tf_vector = tf.fit_transform(specials.lem_tokens.apply(lambda ls: ' '.join(ls))).toarray()

In [74]:
user_recommender = ReviewRecommender()
user_recommender.fit(reviews, specials.special, specials.genre, tf_vector)

In [105]:
user_recommender.pred_one_user(3)[user_recommender.ratings_mat[3].nonzero()[1]]

array([8.89625744, 4.54027886, 1.41322552, 1.19727246, 2.51432752,
       8.2499974 , 4.48579476, 7.29674465, 8.07656304, 2.13860657,
       6.56286158, 6.70143419])

In [114]:
user_recommender.top_n_recs(10, n_recs=10)

['Chris Rock Kill The Messenger London New York Johannesburg 2008 Movie Script',
 'Eddie Izzard Glorious 1997',
 'Todd Glass Act Happy',
 'Lee Mack Going Out Live',
 'Sara Pascoe Ladsladslads 2019',
 'Reggie Watts Spatial',
 'Stewart Lee 90s Comedian 2006',
 'Eddie Izzard Unrepeatable',
 'Ricky Gervais England 2 2010',
 'Eddie Izzard Dress Kill 1999']

In [9]:
reviews.head()

0    1    2    3    4    5    6    7    8    9    11   12   13   14   15   17   18   20   ...  297  298  300  301  302  303  304  305  306  307  308  310  311  312  314  315  316  317
Jeremy_Urquhart    0    8    0    0    0    0    0    0    0    7    8    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
rteodore           0   10    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
garrylane-57132    0   10    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
mariellealien      0   10    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
burlanescuelena    0   10    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0

[5 rows x 280 columns]

In [50]:
user_recommender.ratings_mat[400].nonzero()[1]

array([35, 38, 43, 64], dtype=int32)

In [82]:
user_recommender.specials.iloc[user_recommender.ratings_mat[0].nonzero()[1]]

1               Hannah Gadsby Douglas
9     Jerry Seinfeld 23 Hours To Kill
11                 Sincerely Louis Ck
23           Marc Maron End Times Fun
Name: special, dtype: object

In [107]:
reviews.iloc[10:20]

0    1    2    3    4    5    6    7    8    9    11   12   13   14   15   17   18   ...  298  300  301  302  303  304  305  306  307  308  310  311  312  314  315  316  317
leftbanker-1                       0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
mcdsteve                           0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
PurpleProseOfCairo                 0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
professormeowmeowtheharshcritic    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
killingbill                        0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
garrettjyorke                      0    0   10    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
faithless4734                      0    0    6    0    0    0    0    0    0   10    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
bertalan-olah                      0    0    6    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
jesperandersen91                   0    0    3    0    0    0    0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
iwatchibinge                       0    0    6    0    0    0    0    0    0    6    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0

[10 rows x 280 columns]

In [109]:
user_recommender.ratings_mat[10,user_recommender.ratings_mat[10].nonzero()[1]].toarray()

array([[1]])